version: 2
updates:
  - package-ecosystem: composer
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
