Search.appendIndex(
    [
                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter",
            "name": "Highlighter",
            "summary": "",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html"
        },                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter\u003A\u003AtoHtml\u0028\u0029",
            "name": "toHtml",
            "summary": "",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html#method_toHtml"
        },                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter\u003A\u003AopenContainerWithStyles\u0028\u0029",
            "name": "openContainerWithStyles",
            "summary": "",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html#method_openContainerWithStyles"
        },                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter\u003A\u003AcloseContainer\u0028\u0029",
            "name": "closeContainer",
            "summary": "",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html#method_closeContainer"
        },                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter\u003A\u003AgetDefaultStyles\u0028\u0029",
            "name": "getDefaultStyles",
            "summary": "",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html#method_getDefaultStyles"
        },                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter\u003A\u003AgetCssStylesFromCode\u0028\u0029",
            "name": "getCssStylesFromCode",
            "summary": "Define\u0020an\u0020array\u0020of\u0020css\u0020styles\u0020for\u0020a\u0020given\u0020code\u0020and\u0020default\u0020styles",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html#method_getCssStylesFromCode"
        },                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter\u003A\u003AgetConversionTag\u0028\u0029",
            "name": "getConversionTag",
            "summary": "",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html#method_getConversionTag"
        },                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter\u003A\u003AgetDefinedStyles\u0028\u0029",
            "name": "getDefinedStyles",
            "summary": "",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html#method_getDefinedStyles"
        },                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter\u003A\u003AsetDefinedStyles\u0028\u0029",
            "name": "setDefinedStyles",
            "summary": "",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html#method_setDefinedStyles"
        },                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter\u003A\u003AgetRgbColor\u0028\u0029",
            "name": "getRgbColor",
            "summary": "",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html#method_getRgbColor"
        },                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter\u003A\u003ACONTAINER_TAG",
            "name": "CONTAINER_TAG",
            "summary": "",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html#constant_CONTAINER_TAG"
        },                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter\u003A\u003AEND_OF_LINE_TAG",
            "name": "END_OF_LINE_TAG",
            "summary": "",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html#constant_END_OF_LINE_TAG"
        },                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter\u003A\u003A\u0024conversionTags",
            "name": "conversionTags",
            "summary": "Define\u0020tag\u0020for\u0020html\u0020conversion",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html#property_conversionTags"
        },                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter\u003A\u003A\u0024definedStyles",
            "name": "definedStyles",
            "summary": "",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html#property_definedStyles"
        },                {
            "fqsen": "\\AnsiEscapesToHtml\\Highlighter\u003A\u003A\u0024rgbColors",
            "name": "rgbColors",
            "summary": "",
            "url": "classes/AnsiEscapesToHtml-Highlighter.html#property_rgbColors"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\AnsiEscapesToHtml",
            "name": "AnsiEscapesToHtml",
            "summary": "",
            "url": "namespaces/ansiescapestohtml.html"
        }            ]
);
